import type { Company } from "./types";

export const seedCompanies: Company[] = [
  {
    id: "danal",
    commercialName: "Snacks Danal",
    legalName: "Gabriel Maldonado e Hijos SRL",
    cuit: "30-70861713-6",
    city: "Saldán",
    province: "Córdoba",
    distanceKm: 22,
    segment: "processor",
    evidenceStrength: "direct",
    volumeSignal: "high",
    companySize: "medium",
    contactability: "high",
    website: "https://www.snacksdanal.com.ar/",
    verificationStatus: "verified",
    evidence: [
      {
        claim: "Utiliza papa como materia prima",
        excerpt: "La marca figura públicamente como fabricante de snacks y papas fritas.",
        sourceName: "Directorio de Exportadores de Córdoba",
        sourceUrl: "https://www.exportadoresdecordoba.com/directorio",
        checkedAt: "2026-09-21",
        confidence: 0.96,
      },
    ],
  },
  {
    id: "fills",
    commercialName: "Fills",
    legalName: "Fills S.A.S.",
    cuit: "30-71873604-4",
    city: "Córdoba",
    province: "Córdoba",
    distanceKm: 14,
    segment: "processor",
    evidenceStrength: "direct",
    volumeSignal: "medium",
    companySize: "small",
    contactability: "medium",
    website: "https://www.linkedin.com/company/snacks-fills",
    verificationStatus: "partial",
    evidence: [
      {
        claim: "Produce snacks de papa",
        excerpt: "La identidad societaria está localizada; falta validar capacidad y compra directa.",
        sourceName: "Indicadores",
        sourceUrl: "https://indicadores.ar/empresa/30718736044-fills-s-a-s",
        checkedAt: "2026-09-21",
        confidence: 0.82,
      },
    ],
  },
  {
    id: "fly-kitchen",
    commercialName: "Fly Kitchen",
    legalName: "Fly Kitchen S.A.",
    cuit: "30-70728569-5",
    city: "Córdoba",
    province: "Córdoba",
    distanceKm: 18,
    segment: "catering",
    evidenceStrength: "indirect",
    volumeSignal: "high",
    companySize: "large",
    contactability: "high",
    verificationStatus: "partial",
    evidence: [
      {
        claim: "Opera servicios de alimentación con compras y stock",
        excerpt: "La actividad pública muestra elaboración alimentaria y funciones de compras.",
        sourceName: "Dateas",
        sourceUrl: "https://www.dateas.com/es/empresa/fly-kitchen-sa-30707285695",
        checkedAt: "2026-09-21",
        confidence: 0.8,
      },
    ],
  },
  {
    id: "cordiez",
    commercialName: "Cordiez",
    legalName: "CYRE S.A.",
    cuit: "30-50357927-4",
    city: "Córdoba",
    province: "Córdoba",
    distanceKm: 11,
    segment: "retail",
    evidenceStrength: "indirect",
    volumeSignal: "high",
    companySize: "large",
    contactability: "medium",
    website: "https://www.cordiez.com.ar/",
    verificationStatus: "partial",
    evidence: [
      {
        claim: "Cadena minorista con potencial de compra por volumen",
        excerpt: "La web corporativa identifica la razón social y el CUIT.",
        sourceName: "Cordiez",
        sourceUrl: "https://www.cordiez.com.ar/",
        checkedAt: "2026-09-21",
        confidence: 0.78,
      },
    ],
  },
  {
    id: "servicios-alimentos",
    commercialName: "Servicios de Alimentos",
    legalName: "Servicios de Alimentos S.A.",
    city: "Córdoba",
    province: "Córdoba",
    distanceKm: 28,
    segment: "catering",
    evidenceStrength: "indirect",
    volumeSignal: "high",
    companySize: "medium",
    contactability: "high",
    verificationStatus: "needs_review",
    evidence: [
      {
        claim: "Proveedor institucional de alimentación",
        excerpt: "Aparece asociado a órdenes públicas de servicios de alimentación.",
        sourceName: "COMPR.AR",
        sourceUrl: "https://comprar.gob.ar/",
        checkedAt: "2026-09-21",
        confidence: 0.7,
      },
    ],
  },
  {
    id: "distribuidor-demo",
    commercialName: "Distribuidor por validar",
    city: "Villa María",
    province: "Córdoba",
    distanceKm: 145,
    segment: "distributor",
    evidenceStrength: "none",
    volumeSignal: "unknown",
    companySize: "unknown",
    contactability: "low",
    verificationStatus: "needs_review",
    evidence: [],
  },
];
